# Fly.io app configuration

app = "currency"
primary_region = "sea"

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20

[[http_service.checks]]
grace_period = "10s"
interval = "10s"
timeout = "2s"
method = "GET"
path = "/"

[[vm]]
size = "shared-cpu-1x"
